services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
    restart: always

  simplepaymentproviderservice:
    build:
      context: ./SimplePaymentProviderService
    container_name: simplePaymentProviderService
    ports:
      - "5000:5000"
    restart: always

  backend:
    build:
      context: ./MiniPayPlatformBackend
      dockerfile: Dockerfile
    container_name: minipay-backend
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=MiniPayDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true
    depends_on:
      - sqlserver
    restart: always

  frontend:
    build:
      context: ./MiniPayPlatformFrontend
      dockerfile: Dockerfile
    container_name: minipay-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: always
